# Generated by Django 5.1.1 on 2024-09-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_post_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
