# Generated by Django 5.1.1 on 2024-09-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_rename_category_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
