# Generated by Django 5.1.1 on 2024-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_post_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.CharField(max_length=5000)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
