# Generated by Django 5.1.1 on 2024-09-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='privacy',
            field=models.TextField(max_length=5000),
        ),
    ]
